CREATE OR REPLACE DYNAMIC TABLE NECCDMDEV.DIMENSIONS.DIM_ADDRESSINFO(
    ADDRESSINFO_KEY,
    CITY,
    STREET,
    COUNTRY_KEY,
    ADDRESS_NUMBER,
    VALID_FROM_DATE,
    INTERNATIONAL_ADDRESS_VERSION_ID
) 
TARGET_LAG = '1 DAY'
REFRESH_MODE = INCREMENTAL
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT DISTINCT
    HASH(ADRC.ADDRNUMBER || ADRC.date_from || ADRC.NATION || ADRC.COUNTRY) AS ADDRESSINFO_KEY,
    ADRC.CITY1 AS CITY,
    ADRC.STREET AS STREET,
    ADRC.COUNTRY AS COUNTRY_KEY,
    ADRC.ADDRNUMBER AS ADDRESS_NUMBER,
    ADRC.date_from AS VALID_FROM_DATE,
    ADRC.NATION AS INTERNATIONAL_ADDRESS_VERSION_ID
FROM NECPROD.SALES_AND_DISTRIBUTION.ADRC;
