name: Snowflake Connection

on:
  push:
    branches:
      - main

jobs:
  snowflake_connection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install snowflake-connector-python
          pip install pyyaml

      - name: Retrieve Snowflake private key from GitHub secrets
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > private-key.p8

      - name: Run Python script to connect to Snowflake
        run: |
          python <<EOF
import yaml
import snowflake.connector

# Load the YAML configuration
with open('snowflake_connection.yaml', 'r') as file:
    config = yaml.safe_load(file)

# Extract Snowflake connection details
connection_params = config['snowflake_connection']

# Read the private key file from the GitHub secret
private_key_path = 'private-key.p8'
private_key = open(private_key_path, 'r').read()

# Establish the Snowflake connection
conn = snowflake.connector.connect(
    user=connection_params['svcsnowflakegithub'],
    account=connection_params['necdcsf.east-us-2.azure.snowflakecomputing.com'],
    private_key='${{ secrets.SNOWFLAKE_PRIVATE_KEY }}',
    role=connection_params['NECDATAENGINEER'],
    warehouse=connection_params['COMPUTE_WH'],
    database=connection_params['NECDEV'],
    schema=connection_params['MATERIALS_MANAGEMENT'],
    authenticator=connection_params['snowflake'],
)

# Example query execution
cursor = conn.cursor()
cursor.execute("SELECT CURRENT_DATE")
result = cursor.fetchone()
print(result)

# Clean up
cursor.close()
conn.close()
EOF
