name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install snowflake-connector-python

      - name: Run Snowflake script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        run: |
          python -c "
import os
import snowflake.connector
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend

# Fetch the private key and passphrase from environment variables
private_key_str = os.getenv('SNOWFLAKE_PRIVATE_KEY')  # Private key in PEM format
private_key_passphrase = os.getenv('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE')

# Load the private key from the PEM string
private_key_obj = serialization.load_pem_private_key(
    private_key_str.encode(),  # Convert string to bytes
    password=private_key_passphrase.encode() if private_key_passphrase else None,
    backend=default_backend()
)

# Establish Snowflake connection
conn = snowflake.connector.connect(
    user=os.getenv('SNOWFLAKE_USER'),
    account=os.getenv('SNOWFLAKE_ACCOUNT'),
    private_key=private_key_obj,  # Pass the RSAPrivateKey object directly
)

# Execute your SQL script (replace with your actual SQL query)
conn.cursor().execute('RUN YOUR SQL SCRIPT HERE')

# Optionally, you can close the connection after executing the query
conn.close()
          "
